In [5]:
import numpy as np

# Sample Input/Output
d = 10
n = 1000

np.random.seed(0)
X = np.random.randn(n, d)
Y = np.array([0] * (n // 2) + [1] * (n // 2))
eta = 1e-3
rho = 1e-6
    
class LogisticRegression:
    def __init__(self, d):
        self.w = np.random.randn(d)

    def compute_loss(self, X, Y):
        """
        Compute l(w) with n samples.
        Inputs:
            X  - A numpy array of size (n, d). Each row is a sample.
            Y  - A numpy array of size (n,). Each element is 0 or 1.
        Returns:
            A float.
        """
        self.lw = 0
        for i in range(len(Y)):
            self.lw = ((np.log(1+np.exp(np.dot(self.w, X[i+1])))-np.dot(self.w, X[i+1])*Y[i+1])+self.lw)/len(Y)
        raise NotImplementedError

In [8]:
print(self.lw)

NameError: name 'self' is not defined

In [9]:
x1 = np.arange(9.0).reshape((3, 3))
np.add(x1, 1)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
x1+1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
seed=0
np.random.seed(0)

In [92]:
alpha = np.array([[1, 1, 2, -3, 0, 1, -3], [1, 2, 1, 1, 1, 0, 2], [1, 3, 2, 2, 2, 2, 1], [1, 2, 0, 3, 1, -2, 2]])
x = np.array([1,1,0,1,0,1,1])
a = np.dot(alpha, x)
z = 1/(1+np.exp(-a))

In [93]:
print(z)

[0.04742587 0.99752738 0.99987661 0.99752738]


In [94]:
z_hat = np.append(1, z)
print(z_hat)

[1.         0.04742587 0.99752738 0.99987661 0.99752738]


In [95]:
beta = np.array([[1, 1, 2, -2, 3], [1, 2, -1, 3, 1], [1, 3, 1, -1, 1]])
b = np.dot(beta, z_hat)
print(b)

[4.03530955 4.09448156 2.13745577]


In [96]:
expb = np.exp(b)
print(expb)
sum = np.sum(np.exp(b))
print(sum)
y_hat = np.exp(b)/np.sum(np.exp(b))
print(y_hat)

[56.56042561 60.00822059  8.47784057]
125.04648677219633
[0.45231519 0.4798873  0.06779751]


In [97]:
y = [0, 0, 1]
logyh = np.log(y_hat)
print(logyh)
yy = y*logyh
print(yy)
loss = np.sum(y*np.log(y_hat))
print(loss)

[-0.79337602 -0.734204   -2.69122979]
[-0.         -0.         -2.69122979]
-2.691229794548955


In [98]:
y_ = np.multiply(-1, y)
print(y_)
dldb = y_+np.sum(np.dot(y,y_hat))
print(dldb)

[ 0  0 -1]
[ 0.06779751  0.06779751 -0.93220249]


In [100]:
z_append = np.array([z_hat])
print(z_append)
dldbeta = np.dot(z_append.T, [dldb])
print(dldbeta)

[[1.         0.04742587 0.99752738 0.99987661 0.99752738]]
[[ 0.06779751  0.06779751 -0.93220249]
 [ 0.00321536  0.00321536 -0.04421052]
 [ 0.06762987  0.06762987 -0.9298975 ]
 [ 0.06778915  0.06778915 -0.93208746]
 [ 0.06762987  0.06762987 -0.9298975 ]]


In [89]:
print(dldb)

NameError: name 'dldb' is not defined

In [61]:
beta_star = np.array([[1, 2, -2, 3], [2, -1, 3, 1], [3, 1, -1, 1]])
print(beta_star)

[[ 1  2 -2  3]
 [ 2 -1  3  1]
 [ 3  1 -1  1]]


In [63]:
dldz = np.dot(dldb, beta_star)
print(dldz)

[-2.59321493 -0.86440498  1.         -0.66101244]


In [65]:
dlda = dldz*z*(1-z)
print(dlda)



[-0.11715279 -0.00213206  0.00012338 -0.00163039]


In [71]:

dldalpha = np.dot(np.transpose([x]), [dlda])
print(dldalpha)

[[-0.11715279 -0.00213206  0.00012338 -0.00163039]
 [-0.11715279 -0.00213206  0.00012338 -0.00163039]
 [-0.         -0.          0.         -0.        ]
 [-0.11715279 -0.00213206  0.00012338 -0.00163039]
 [-0.         -0.          0.         -0.        ]
 [-0.11715279 -0.00213206  0.00012338 -0.00163039]
 [-0.11715279 -0.00213206  0.00012338 -0.00163039]]


In [72]:
beta_norm = np.linalg.norm(beta_star)
print(beta_norm)


6.708203932499369


In [74]:
alpha_star = np.array([[1, 2, -3, 0, 1, -3], [2, 1, 1, 1, 0, 2], [3, 2, 2, 2, 2, 1], [2, 0, 3, 1, -2, 2]])
print(alpha_star)
alpha_norm = np.linalg.norm(alpha_star)
L = -loss+0.01*(alpha_norm**2+beta_norm**2)
print(L)

[[ 1  2 -3  0  1 -3]
 [ 2  1  1  1  0  2]
 [ 3  2  2  2  2  1]
 [ 2  0  3  1 -2  2]]
3.9712297945489548


In [1]:
from net import NeuralNetwork

In [2]:
model = NeuralNetwork()

In [5]:
model.forward([1, 2, 3])

TypeError: forward() missing 1 required positional argument: 'x'

In [123]:
import numpy as np
biases = [np.array([0.2, 0.0, -0.2]), np.array([0.5])]
L = len(biases) 
print(L)

2


In [124]:
print(biases[0])

[ 0.2  0.  -0.2]


In [125]:
weights = [np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]), np.array([[-0.1], [-0.2], [-0.3]])]
x = np.array([1., 2.])
#fx = np.dot(weights[0], x)

In [14]:
print(fx)

[0.9 1.2 1.5]


In [54]:
x_prev = x
Fx = []
for l in range(L-1):
            # Fx = self.sigmoid(self.weights[l].T @ xprev + self.biases[l])
    output = 1/(1+np.exp(np.dot(np.transpose(weights[l]), x_prev)+biases[l]))
    Fx.append(output)
    x_prev = output
    
            
        
Fxx = np.dot(np.transpose(weights[L-1]), x_prev)+biases[L-1]


In [55]:
print(Fxx)

[0.36448146]


In [45]:
print(range(L-2))

range(0, 0)


In [47]:
for i in range(0):
    print(i)

In [48]:
print(range(0))

range(0, 0)


In [56]:
Z = []
A = []
for b, W in zip(biases, weights):
    z = W.T @ a + b if Z else z = W.T @ x + b
    a = 1 / (1+np.exp(-z))
    Z.append(z)
    A.append(a)

SyntaxError: cannot assign to conditional expression (2590723526.py, line 4)

In [146]:
s = []
W_grad = []
b_grad = []
x_prev = x
for l in range(L-1):
            # Fx = self.sigmoid(self.weights[l].T @ xprev + self.biases[l])
    output = 1/(1+np.exp(-(np.dot(np.transpose(weights[l]), x_prev)+biases[l])))
    s.append(output)
    x_prev = output

In [147]:
for k in range(L-1, -1, -1):
    inter = s[k]*(1-s[k])*np.dot(weights[k+1], inter) if k != L-1 else np.array([1])
    b_grad[k] = inter
    W_grad[k] = np.dot(output[k-1], inter.T) if k!= 0 else np.matmul(np.transpose([x]), [inter])
            

IndexError: list assignment index out of range

In [145]:
print(W_grad)

[array([[0.16527857, 0.16804645, 0.17076132],
       [0.33055715, 0.33609289, 0.34152265]]), array([0.69919277])]


In [141]:
inter = np.array([1])
W_grad[1] = np.dot(output[k-1], inter.T)
b_grad[1] = inter
print(W_grad[1])

[0.68083359]


In [142]:
print(weights)

[array([[0.14057615, 0.1334671 , 0.12626755],
       [0.28115229, 0.2669342 , 0.25253509]]), array([0.78583498])]


In [ ]:
W_grad = [np.zeros(W.shape) for b in self.weights]
b_grad = [np.zeros(b.shape) for W in self.weights]